spring:
  application:
    name: customer
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

jwt:
  secret-key: secret-secret-secret-secret-secret-secret # at least 32 character
  valid-time: 24 # hours